import { SessionInfoV2 } from "./models";
import { EQUIP_META, EquipSlotState, EquipState, SessionBonus } from "./tt-models.v3";
import { TTCoreService } from "./tt-core.service";
import { DefaultMap } from "./utils";

export function createEmptySessionBonus(): SessionBonus {
    return {
        stats: {
            str: 0, agi: 0, vit: 0, int: 0, dex: 0, luk: 0,
            maxHP: 0, maxSP: 0, maxHPRate: 0, maxSPRate: 0,
            hpRegenRate: 0, spRegenRate: 0, hpRecovRate: 0, spRecovRate: 0,
            hpLossRate: 0, spLossRate: 0,
            atk: 0, atk2: 0, atkRate: 0, baseAtk: 0,
            hit: 0, hitRate: 0, critical: 0, critAtkRate: 0, criticalLong: 0,
            aspd: 0, aspdRate: 0, longAtkRate: 0, shortAtkRate: 0,
            atkEle: 'neutral', atkRange: 0, splashRange: 0,
            doubleRate: 0, doubleAddRate: 0, perfectHitRate: 0, perfectHit: 0,
            matk: 0, matk2: 0, matkRate: 0, minMatk: 0,
            variableCastrate: 0, fixedCastrate: 0, castrate: 0, delayRate: 0,
            healPower: 0, healPower2: 0,
            def: 0, def2: 0, defRate: 0, def2Rate: 0, mdef: 0, mdef2: 0, mdefRate: 0,
            defEle: 'neutral', flee: 0, flee2: 0, fleeRate: 0, longAtkDef: 0, nearAtkDef: 0,
            magicAtkDef: 0, miscAtkDef: 0, reduceMagicReturn: 0, reduceMeleeReturn: 0,
            skillLongAtkDef: 0, noWeaponDamage: 0, noMagicDamage: 0,
            res: 0, mres: 0, speedRate: 0,
            magicHPGainValue: 0, magicSPGainValue: 0,
            hpDrainRate: 0, spDrainRate: 0, hpDrainValue: 0, spDrainValue: 0,
            shortWeaponDamageReturn: 0, longWeaponDamageReturn: 0, magicDamageReturn: 0,
            scIncAtkRate: 0,
            breakArmorRate: 0, breakWeaponRate: 0,
            freeCastMoveRate: 0, addItemHealRate: 0, hpGainValue: 0, tripleAddRate: 0,
            spGainValue: 0, useSPrate: 0, scAtkPotion: 0, scMatkPotion: 0, scIncCrit: 0,
            scCastRate: 0
        },
        // initialze maps
        addRace: new DefaultMap(0), addEle: new DefaultMap(0), addSize: new DefaultMap(0), addClass: new DefaultMap(0), addRace2: new DefaultMap(0),
        magicAddRace: new DefaultMap(0), magicAddRace2: new DefaultMap(0), magicAddEle: new DefaultMap(0), magicAddSize: new DefaultMap(0), magicAddClass: new DefaultMap(0), magicAtkEle: new DefaultMap(0),
        subRace: new DefaultMap(0), subEle: new DefaultMap(0), subSize: new DefaultMap(0), subClass: new DefaultMap(0), subRace2: new DefaultMap(0),
        ignoreDefRace: new DefaultMap(false), ignoreDefClass: new DefaultMap(false), ignoreMdefRace: {}, ignoreMdefClass: {}, ignoreDefRaceRate: new DefaultMap(0),
        skillAtk: new DefaultMap(0), skillUseSP: new DefaultMap(0), skillCooldown: {},
        skillFixedCast: {}, skillVariableCast: {}, criticalAddRace: new DefaultMap(0),
        addDamageClass: new DefaultMap(0), ignoreMdefRaceRate: new DefaultMap(0), ignoreMdefClassRate: new DefaultMap(0),
        resEff: new DefaultMap(0), skillCritAtkRate: new DefaultMap(0), ignoreMdefRace2Rate: new DefaultMap(0),
        skillHeal: new DefaultMap(0), expAddRace: new DefaultMap(0), addMagicDamageClass: new DefaultMap(0), ignoreMdefEleRate: new DefaultMap(0),
        expAddClass: new DefaultMap(0), addDefMonster: new DefaultMap(0), kickAddRate: new DefaultMap(0),
        addItemSPHealRate: new DefaultMap(0), skillDelayrate: new DefaultMap(0), skillHeal2: new DefaultMap(0), criticalAddEle: new DefaultMap(0),
        castrate: new DefaultMap(0), skillDefRatioAtkClass: new DefaultMap('all'), skillWeaponElement: new DefaultMap('neutral'),
        // falgs will start empty
        flags: new DefaultMap(false)
    };
}
export function defaultEquipSlotState(): EquipSlotState {
    return {
        item: 0,
        refine: 0,
        cards: [],
        enchants: []
    }
}
export function defaultEquipState(): EquipState {
    return Object.fromEntries(
        Object.keys(EQUIP_META).map(slot => [slot, defaultEquipSlotState()])
    ) as EquipState;
}

export const SESSION_INFO_DEFAULT: SessionInfoV2 = {
    baseLevel: 1,
    jobLevel: 1,
    baseLevelMax: TTCoreService.MAX_LVL,
    jobLevelMax: 10,
    weaponAtk: 0,
    vanillaMode: 'Unrestricted',
    baseStats: {
        str: 1,
        agi: 1,
        vit: 1,
        int: 1,
        dex: 1,
        luk: 1
    },
    activeBonus: {
        str: 0,
        agi: 0,
        vit: 0,
        int: 0,
        dex: 0,
        luk: 0,
        allStats: 0,
        hit: 0,
        perfectHitRate: 0,
        flee: 0,
        crit: 0,
        criticalAtkRate: 0,
        perfectDodge: 0,
        aspd: 0,
        aspdRate: 0,
        maxHp: 0,
        maxSp: 0,
        maxHpRate: 0,
        maxSpRate: 0,
        matk: 0,
        matkRate: 0,
        atk: 0,
        atkRate: 0,
        shortAtkRate: 0,
        longAtkRate: 0,
        longAtkDef: 0,
        def: 0,
        defRate: 0,
        nearAtkDef: 0,
        magicAtkDef: 0,
        miscAtkDef: 0,
        defRatioAtkClass: 0,
        mdef: 0,
        armorElement: "neutral",
        weaponElement: "neutral",
        ignoreDefClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        ignoreMdefClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        ignoreDefRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        ignoreMdefRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        ignoreDefElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        ignoreMdefElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        addClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        magicAddClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        expAddClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        subClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        addSize: {
            small: 0,
            medium: 0,
            large: 0,
        },
        subSize: {
            small: 0,
            medium: 0,
            large: 0,
        },
        addRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        magicAddRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        addRace2: {
            goblin: 0,
            golem: 0,
            orc: 0,
            kobold: 0,
            manuk: 0,
            splendide: 0,
            biolab: 0,
            kiel: 0,
            juperos: 0,
        },
        magicAddRace2: {
            goblin: 0,
            golem: 0,
            orc: 0,
            kobold: 0,
            manuk: 0,
            splendide: 0,
            biolab: 0,
            kiel: 0,
            juperos: 0,
        },
        subRace2: {
            goblin: 0,
            golem: 0,
            orc: 0,
            kobold: 0,
            manuk: 0,
            splendide: 0,
            biolab: 0,
            kiel: 0,
            juperos: 0,
        },
        criticalAddRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        criticalAtkRateRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        expAddRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        subRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        addElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        magicAddElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        magicElementRate: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        expAddElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        subElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        subDefElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        addEffect: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        magicAddEffect: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        addEffectWhenHit: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        resEffect: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        breakArmorRate: 0,
        breakWeaponRate: 0,
        reflectShortWeaponDamage: 0,
        spCostReductionRate: 0,
        hpDrainRate: {
            chance: 0,
            value: 0,
        },
        spDrainRate: {
            chance: 0,
            value: 0,
        },
        hpRecoveryRate: 0,
        spRecoveryRate: 0,
        castRate: 0,
        castDelay: 0,
        healPower: {
            all: 0,
            heal: 0,
            sanctuary: 0,
            potionPitcher: 0,
            slimPotionPitcher: 0,
        },
        healPower2: {
            all: 0,
            heal: 0,
            sanctuary: 0,
            potionPitcher: 0,
            slimPotionPitcher: 0,
        },
        addGlobalItemHealRate: 0,
        addGlobalSpItemHealRate: 0,
        addItemHealRate: {},
        addItemGlobalHealRate: {},
        allowsRefine: true,
        isUnbreakable: false,
        addMonster: {},
        addDefMonster: {},
        skillAtk: {},
        autospell: {},
        enableSkill: {},
        skillCastRate: {},
        skillCastDelay: {},
        scPdFood: 0,
        scStrFood: 0,
        scAgiFood: 0,
        scVitFood: 0,
        scIntFood: 0,
        scDexFood: 0,
        scLukFood: 0,
        scHitFood: 0,
        scIncCrit: 0,
        scDefRate: 0,
        scMdefRate: 0,
        scCastRate: 0,
        scFleeFood: 0,
        scExpBoost: 0,
        scJexpBoost: 0,
        scAtkPotion: 0,
        scMatkPotion: 0,
        scAspdPotion: 0,
        scIncAtkRate: 0,
        scIncMatkRate: 0,
        scIncAspdRate: 0,
        scIncreaseAgi: 0,
    },
    activeStatus: {
        Sprint: 0,
        "Lex Aeterna": 0,
        Eska: 0
    },
    equip: {
        upperHg: '(No Upper Headgear)',
        middleHg: '(No Middle Headgear)',
        lowerHg: '(No Lower Headgear)',
        armor: '(No Armor)',
        rightHand: 'Unarmed',
        rightHandType: 'Unarmed',
        leftHand: 'Unarmed',
        leftHandType: 'Unarmed',
        garment: '(No Garment)',
        shoes: '(No Footgear)',
        rhAccessory: '(No Accessory)',
        lhAccessory: '(No Accessory)',
    },
    refine: {
        armor: 0,
        garment: 0,
        leftHand: 0,
        lhAccessory: 0,
        lowerHg: 0,
        middleHg: 0,
        rhAccessory: 0,
        rightHand: 0,
        shoes: 0,
        upperHg: 0
    },
    card: {
        upperHg: '',
        middleHg: '',
        armor: '',
        rightHand: ['', '', '', ''],
        leftHand: ['', '', '', ''],
        garment: '',
        shoes: '',
        rhAccessory: '',
        lhAccessory: '',
    },
    enchant: {
        middleHg: [],
        armor: [],
        rightHand: [],
        leftHand: [],
        garment: [],
        shoes: [],
        rhAccessory: [],
        lhAccessory: [],
    },
    activeFood: {
        Stats: {
            STR: 'STR+0',
            AGI: 'AGI+0',
            VIT: 'VIT+0',
            INT: 'INT+0',
            DEX: 'DEX+0',
            LUK: 'LUK+0',
        },
        'New World': {
            'Rune Strawberry Cake': false,
            'Schwartzwald Pine Jubilee': false,
            'Arunafeltz Desert Sandwich': false,
            "Manuk's Sturdiness": false,
            "Manuk's Faith": false,
            "Manuk's Will": false,
            "Pinguicula's Fruit Jam": false,
            "Cornus' Tear": false,
            "Luciola's Honey Jam": false,
        },
        BG: {
            'Military Ration B': false,
            'Military Ration C': false,
            'Tasty Pink Ration': false,
            'Tasty White Ration': false,
        },
        'Summer Cocktails': {
            "Venatu's Beep": false,
            "Old Dracula's Mix": false,
            'Spammers Heaven': false,
            "Myst Case's Surprise": false,
            'Seductive Bathory': false,
            "Sting's Slap": false,
            'Blossoming Geographer': false,
            'Drip of Yggdrasil': false,
            'Moscow Headless Mule': false,
            "Bobo's Boba": false,
            "Wolfchev's Nightcap": false,
            "Chepet's Match": false,
            "Dullahan's Ale": false,
            "Sippin' Galapago": false,
            "Sleeper's Dream": false,
            "Mobster's Paradise": false,
        },
        Misc: {
            Abrasive: false,
            'Buche de Noël': false,
            'Guarana Candy': false,
            'Greater Agimat of Ancient Spirit': false,
            'Box of Resentment': false,
            'Box of Drowsiness': false,
            'Sesame Pastry': false,
            'Honey Pastry': false,
            'Rainbow Cake': false,
        },
        Resistance: {
            'Coldproof Potion': false,
            'Earthproof Potion': false,
            'Fireproof Potion': false,
            'Thunderproof Potion': false,
        },
        Eclage: {
            'Snow Flip': false,
            'Peony Mommy': false,
            'Slapping Herb': false,
            'Yggdrasil Dust': false,
        },
        Eden: {
            'Rough Energy Crystal': false,
            'Purified Energy Crystal': false,
            'High Energy Crystal': false,
        }
    },
    passiveSkill: {
        Dragonology: 0,
        'Cavalier Mastery': 0,
        'Fighting Chant': 0,
        'Sword Mastery': 0,
        'Two-handed Sword Mastery': 0,
        'Spear Mastery': 0,
        'Axe Mastery': 0,
        'Katar Mastery': 0,
        'Advanced Katar Mastery': 0,
        'Advanced Book': 0,
        'Musical Lesson': 0,
        'Dance Lesson': 0,
        'Iron Hand': 0,
        'Throw Shuriken': 0,
        'Sonic Acceleration': 0,
        'Sprint Unarmed': 0,
        'Demon Bane': 0,
        'Beast Bane': 0,
        'Steel Crow': 0,
        'Weaponry Research': 0,
        'Hilt Binding': 0,
        'Triple Action': 0,
        'Hunter Link': 0,
        'Crusader Link': 0,
        'Assassin Link': 0,
    },
    activeBuff: {
        isMaximizePowerActive: false,
        'Active Spheres': 0,
        'Aura Blade': 0,
        'Magnum Break': 0,
        'Endless Deadly Poison': 0,
        'True Sight': 0,
        Deluge: 0,
        Volcano: 0,
        'Violent Gale': 0,
    }
}