import { SessionChangeEvent, SessionInfoV2 } from "./models";
import { TTCoreService } from "./tt-core.service";

export const SESSION_INFO_DEFAULT: SessionInfoV2 = {
    changeEvent: SessionChangeEvent.INIT,
    baseLevel: 1,
    jobLevel: 1,
    baseLevelMax: TTCoreService.MAX_LVL,
    jobLevelMax: 10,
    weaponAtk: 0,
    ammoType: '',
    vanillaMode: 'Unrestricted',
    baseStats: {
        str: 1,
        agi: 1,
        vit: 1,
        int: 1,
        dex: 1,
        luk: 1
    },
    activeBonus: {
        str: 0,
        agi: 0,
        vit: 0,
        int: 0,
        dex: 0,
        luk: 0,
        allStats: 0,
        hit: 0,
        perfectHitRate: 0,
        flee: 0,
        crit: 0,
        criticalAtkRate: 0,
        perfectDodge: 0,
        aspd: 0,
        aspdRate: 0,
        maxHp: 0,
        maxSp: 0,
        maxHpRate: 0,
        maxSpRate: 0,
        matk: 0,
        matkRate: 0,
        atk: 0,
        atkRate: 0,
        shortAtkRate: 0,
        longAtkRate: 0,
        longAtkDef: 0,
        def: 0,
        defRate: 0,
        nearAtkDef: 0,
        magicAtkDef: 0,
        miscAtkDef: 0,
        defRatioAtkClass: 0,
        mdef: 0,
        armorElement: 0,
        weaponElement: 0,
        ignoreDefClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        ignoreMdefClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        ignoreDefRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        ignoreMdefRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        ignoreDefElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        ignoreMdefElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        addClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        magicAddClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        expAddClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        subClass: {
            all: 0,
            normal: 0,
            boss: 0,
            guardian: 0,
        },
        addSize: {
            small: 0,
            medium: 0,
            large: 0,
        },
        subSize: {
            small: 0,
            medium: 0,
            large: 0,
        },
        addRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        magicAddRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        addRace2: {
            goblin: 0,
            golem: 0,
            orc: 0,
            kobold: 0,
            manuk: 0,
            splendide: 0,
            biolab: 0,
            kiel: 0,
            juperos: 0,
        },
        magicAddRace2: {
            goblin: 0,
            golem: 0,
            orc: 0,
            kobold: 0,
            manuk: 0,
            splendide: 0,
            biolab: 0,
            kiel: 0,
            juperos: 0,
        },
        subRace2: {
            goblin: 0,
            golem: 0,
            orc: 0,
            kobold: 0,
            manuk: 0,
            splendide: 0,
            biolab: 0,
            kiel: 0,
            juperos: 0,
        },
        criticalAddRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        criticalAtkRateRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        expAddRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        subRace: {
            formless: 0,
            undead: 0,
            brute: 0,
            plant: 0,
            insect: 0,
            fish: 0,
            demon: 0,
            demiHuman: 0,
            angel: 0,
            dragon: 0,
        },
        addElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        magicAddElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        magicElementRate: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        expAddElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        subElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        subDefElement: {
            neutral: 0,
            water: 0,
            earth: 0,
            fire: 0,
            wind: 0,
            poison: 0,
            holy: 0,
            shadow: 0,
            ghost: 0,
            undead: 0,
        },
        addEffect: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        magicAddEffect: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        addEffectWhenHit: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        resEffect: {
            poison: 0,
            stun: 0,
            freeze: 0,
            curse: 0,
            blind: 0,
            sleep: 0,
            silence: 0,
            confusion: 0,
            bleeding: 0,
            stone: 0,
        },
        breakArmorRate: 0,
        breakWeaponRate: 0,
        reflectShortWeaponDamage: 0,
        spCostReductionRate: 0,
        hpDrainRate: {
            chance: 0,
            value: 0,
        },
        spDrainRate: {
            chance: 0,
            value: 0,
        },
        hpRecoveryRate: 0,
        spRecoveryRate: 0,
        castRate: 0,
        castDelay: 0,
        healPower: {
            all: 0,
            heal: 0,
            sanctuary: 0,
            potionPitcher: 0,
            slimPotionPitcher: 0,
        },
        healPower2: {
            all: 0,
            heal: 0,
            sanctuary: 0,
            potionPitcher: 0,
            slimPotionPitcher: 0,
        },
        addGlobalItemHealRate: 0,
        addGlobalSpItemHealRate: 0,
        addItemHealRate: {},
        addItemGlobalHealRate: {},
        allowsRefine: true,
        isUnbreakable: false,
        addMonster: {},
        addDefMonster: {},
        skillAtk: {},
        autospell: {},
        enableSkill: {},
        skillCastRate: {},
        skillCastDelay: {},
        scPdFood: 0,
        scStrFood: 0,
        scAgiFood: 0,
        scVitFood: 0,
        scIntFood: 0,
        scDexFood: 0,
        scLukFood: 0,
        scHitFood: 0,
        scIncCrit: 0,
        scDefRate: 0,
        scMdefRate: 0,
        scCastRate: 0,
        scFleeFood: 0,
        scExpBoost: 0,
        scJexpBoost: 0,
        scAtkPotion: 0,
        scMatkPotion: 0,
        scAspdPotion: 0,
        scIncAtkRate: 0,
        scIncMatkRate: 0,
        scIncAspdRate: 0,
        scIncreaseAgi: 0,
    },
    activeStatus: {
        Sprint: 0
    },
    equip: {
        upperHg: '',
        middleHg: '',
        lowerHg: '',
        armor: '',
        rightHand: 'Unarmed',
        rightHandType: 'Unarmed',
        leftHand: 'Unarmed',
        leftHandType: 'Unarmed',
        garment: '',
        shoes: '',
        rhAccessory: '',
        lhAccessory: '',
    },
    refine: {
        armor: 0,
        garment: 0,
        leftHand: 0,
        lhAccessory: 0,
        lowerHg: 0,
        middleHg: 0,
        rhAccessory: 0,
        rightHand: 0,
        shoes: 0,
        upperHg: 0
    },
    card: {
        upperHg: '',
        middleHg: '',
        armor: '',
        rightHand: ['', '', '', ''],
        leftHand: ['', '', '', ''],
        garment: '',
        shoes: '',
        rhAccessory: '',
        lhAccessory: '',
    },
    enchant: {
        middleHg: [],
        armor: [],
        rightHand: [],
        leftHand: [],
        garment: [],
        shoes: [],
        rhAccessory: [],
        lhAccessory: [],
    },
    activeFood: {
        Stats: {
            STR: 'STR+0',
            AGI: 'AGI+0',
            VIT: 'VIT+0',
            INT: 'INT+0',
            DEX: 'DEX+0',
            LUK: 'LUK+0',
        },
        'New World': {
            'Rune Strawberry Cake': false,
            'Schwartzwald Pine Jubilee': false,
            'Arunafeltz Desert Sandwich': false,
            "Manuk's Sturdiness": false,
            "Manuk's Faith": false,
            "Manuk's Will": false,
            "Pinguicula's Fruit Jam": false,
            "Cornus' Tear": false,
            "Luciola's Honey Jam": false,
        },
        BG: {
            'Military Ration B': false,
            'Military Ration C': false,
            'Tasty Pink Ration': false,
            'Tasty White Ration': false,
        },
        'Summer Cocktails': {
            "Venatu's Beep": false,
            "Old Dracula's Mix": false,
            'Spammers Heaven': false,
            "Myst Case's Surprise": false,
            'Seductive Bathory': false,
            "Sting's Slap": false,
            'Blossoming Geographer': false,
            'Drip of Yggdrasil': false,
            'Moscow Headless Mule': false,
            "Bobo's Boba": false,
            "Wolfchev's Nightcap": false,
            "Chepet's Match": false,
            "Dullahan's Ale": false,
            "Sippin' Galapago": false,
            "Sleeper's Dream": false,
            "Mobster's Paradise": false,
        },
        Misc: {
            Abrasive: false,
            'Buche de Noël': false,
            'Guarana Candy': false,
            'Greater Agimat of Ancient Spirit': false,
            'Box of Resentment': false,
            'Box of Drowsiness': false,
            'Sesame Pastry': false,
            'Honey Pastry': false,
            'Rainbow Cake': false,
        },
        Resistance: {
            'Coldproof Potion': false,
            'Earthproof Potion': false,
            'Fireproof Potion': false,
            'Thunderproof Potion': false,
        },
        Eclage: {
            'Snow Flip': false,
            'Peony Mommy': false,
            'Slapping Herb': false,
            'Yggdrasil Dust': false,
        },
        Eden: {
            'Rough Energy Crystal': false,
            'Purified Energy Crystal': false,
            'High Energy Crystal': false,
        }
    }
}